### ISSUE TITLE
Copilação!

### ISSUE THREAD

**Issue by kriffx** [Spell-Master/Arcadia#1]
O projeto não está copilando corretamente.
http://prntscr.com/i40e2w

**Comment by Spell-Master** [comment]
Olá. Só por auto segundo a imagem que mostrou fiz uma varredura do código fonte do emulador em busca do problema, analisando o que pode ter gerado o erro em cadeia LNK2019. E aparentemente não há nada de irregular. 
Então fiz o teste de compilação e como pode ver nessa imagem o emulador está compilando normalmente na plataforma windows. (Compilado 22/01/2018)
[https://i.imgur.com/LTZ1uWq.png](url)
E como pode ver aqui no boot Travis a compilação também está normal para sistemas Linux o que é a prioridade.
[https://travis-ci.org/Spell-Master/Arcadia](url)

Acredito que possa ter ocorrido algum erro referente a visual studio que usou.
Se puder me enviar todo LOG de erro apresentado durante a compilação, ficaria mais fácil de eu identificar a origem, pois o primeiro erro gerou outro e esse outro gerou outros "como uma bola de nele"
Dentro dos próximos meses estarei com tempo livre para voltar a trabalhar nesse emulador e farei mais testes usando as versões do visual studio mais recentes.

- O programa de versão visual studio que utilizei se encontra o link na página inicial do emulador.
- Os arquivos EXE gerados nesse teste de compilação estão aqui [https://mega.nz/#!jQMUhaDb!fBI0ZsL7a-uJdOTEdKaKtbDbqx6v9a_YULsE4WXYfJg](url)

**Comment by kriffx** [comment]
Muito obrigado por responder ao meu problema, eu fiz download da versão VS12 e resolveu o meu problema mesmo copilando no VS17.
