### ISSUE TITLE
Sprakki não reconhece meu nome

### ISSUE THREAD

**Issue by kriffx** [Spell-Master/Arcadia#2]
Olá, eu denovo D:
Mal comecei e encontrei um bug no npc da Sprakki, quando converso com ela no campo de treinamento e me pede para ir para dentro do castelo, ao falar com a mesma, pede meu nome conforme foi cadastrado sendo maiúscula ou minúsculas e mesmo digitando exatamente, ela diz que não digitei corretamente. **(Obs.: depurrei o problema e me parece que está comendo a última palavra e para conseguir ir adiante preciso repetir a última palavra, sendo que, "teste" eu ponho "testee")**

![screenarcadia000](https://user-images.githubusercontent.com/21046931/35274863-df32d438-0024-11e8-8037-87cb0a301e74.jpg)
![screenarcadia001](https://user-images.githubusercontent.com/21046931/35274864-df596260-0024-11e8-8b61-2031651d245c.jpg)
![screenarcadia002](https://user-images.githubusercontent.com/21046931/35274865-df7b4fb0-0024-11e8-8351-db47e794dc5b.jpg)

**Comment by Spell-Master** [comment]
Pode ser o seu client que está apresentando problemas, tente ir ao clientinfo.xml e adicionar o lang tipo 9 é o mais parecido com o idioma português brasileiro ao qual o emulador está sendo projetado.
<langtype>9</langtype>

**Comment by Spell-Master** [comment]
Olá. Você poderia me dar algumas informações para que eu possa depurar o suposto bug?
Qual a versão do client exe (hexed) que estava utilizando quando isso aconteceu?
E poderia mostrar seu clientinfo.xml? (Pode ocultar o IP transcrito nele)
