### ISSUE TITLE
Portal bugado

### ISSUE THREAD

**Issue by kriffx** [Spell-Master/Arcadia#3]
Eita, encontrei um portal bugado na guilda dos gatunos, ao entrar foi tudo de boa e ao terimnar de falar com o npc "Gatuna Ajudante" e fui-me ao portal e entrei... voltei para onde estava que era ao lado do portal, mas ainda do lado de dentro.

![screenarcadia000](https://user-images.githubusercontent.com/21046931/35282526-dd63f6c4-003c-11e8-97d4-abf1dca788cd.jpg)

**Comment by Spell-Master** [comment]
Primeiramente muito obrigado por reportar.
Na verdade eu já sabia que "muitos" mas muitos portais estão com erros.
Todos os npcs que foram adicionados, foi eu mesmo quem os criou, por isso tudo já implementado está em português.
E no caso dos portais além de criar-los também desenvolvi o sistema de navegação em conjunto, para dar conta tive que fazer as pressas, por isso a margem de erro é enorme.
Esses são erros simples e bobos que seriam solucionados conforme eu passasse para os testes práticos com o emulador e client (que também está sendo desenvolvido para o emulador).

Em todo caso, obrigado por mostrar o erro e ele foi corrigido (Você pode atualizar o emulador ou fazer as modificações manualmente).
[https://github.com/Spell-Master/Arcadia/commit/050aa4ee146e07ee92df27283ad1ee3634aa0da5](url)
